version: '3.7'

services:
  web: 
    build:
      context: .
    container_name: django_app
    command: ["gunicorn", "proyecto.wsgi:application", "--bind", "0.0.0.0:8000"]

    volumes:
      - .:/proyecto
      - static_volume:/proyecto/statics
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: proyecto.settings
      DATABASE_URL: postgres://cindy:cindy123451@localhost:5432/proyecto

  db:
    image: postgres:14.15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: cindy
      POSTGRES_PASSWORD: cindy123451
      POSTGRES_DB: proyecto

volumes:
  postgres_data:
  static_volume:

